spring:
  application:
    name: "banking-api"
    owner: "Jan Matusewicz"
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

application.base-url: "${SERVICE_BASE_URL:http://localhost:8080}"